<#
    .SYNOPSIS
    Cleanup Script for "Apple of Discord" (Trigger3)
    Removes artifacts, registry keys, and dummy files generated by the simulation.

    .DESCRIPTION
    1. Removes HKCU Run Key "DiscordOverlayUpdater"
    2. Deletes Work Directory (%TEMP%\AppleOfDiscord)
    3. Deletes Secret Directory (C:\Project_Troy)
#>

$ErrorActionPreference = "SilentlyContinue"
Write-Host "[*] Initiating Cleanup for 'Apple of Discord'..." -ForegroundColor Cyan

# 1. Clean Registry
$RegPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
$RegName = "DiscordOverlayUpdater"

if (Get-ItemProperty -Path $RegPath -Name $RegName -ErrorAction SilentlyContinue) {
    Remove-ItemProperty -Path $RegPath -Name $RegName
    Write-Host "    [+] Removed Registry Key: $RegName" -ForegroundColor Green
}
else {
    Write-Host "    [-] Registry Key not found (Already clean)." -ForegroundColor Gray
}

# 2. Clean Work Directory
$WorkDir = "$env:TEMP\AppleOfDiscord"
if (Test-Path $WorkDir) {
    Remove-Item -Path $WorkDir -Recurse -Force
    Write-Host "    [+] Removed Work Directory: $WorkDir" -ForegroundColor Green
}
else {
    Write-Host "    [-] Work Directory not found." -ForegroundColor Gray
}

# 3. Clean Secret Directory
$SecretDir = "C:\Project_Troy"
if (Test-Path $SecretDir) {
    Remove-Item -Path $SecretDir -Recurse -Force
    Write-Host "    [+] Removed Secret Directory: $SecretDir" -ForegroundColor Green
}
else {
    Write-Host "    [-] Secret Directory not found." -ForegroundColor Gray
}

Write-Host "`n[*] Cleanup Complete. The system is clean." -ForegroundColor Cyan